FROM python:3.9-slim

WORKDIR /app

COPY reddit /app/reddit

COPY requirements.txt /app

COPY .env /app

RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app/reddit

CMD python cold_start_subreddit.py && python reddit_crawler.py